### ISSUE TITLE
Any schedule for open source code?

### ISSUE THREAD

**Issue by skykiseki** [yinzhangyue/EoT#1]
Looking forward to the execution code, eagerly

**Comment by yinzhangyue** [comment]
Hi @skykiseki,

Thank you for your interest and for reaching out! We are currently in the process of organizing and preparing the related code for release. We understand the importance of facilitating experiments and reducing the cost of experimentation for everyone. To that end, we will also be providing the initial stage model's output results, along with the final outputs from the EoT method.

Compiling these resources and ensuring they are user-friendly takes a bit of time, but we are committed to making everything available to you. We are aiming to have all these resources released within this month. Please stay tuned for updates, and we appreciate your patience and anticipation.

Best regards~

**Comment by yinzhangyue** [comment]
Hi @skykiseki,

We're excited to announce that our code has now been made open-source! Thank you so much for your interest and patience. 

Feel free to dive into our repository, and don't hesitate to reach out if you have any questions or need further assistance. Your support and attention to our project are greatly appreciated!

Best regards~
